import React from 'react';

const Privacy = () => {
  return (
    <div>
      <section
        className="section"
        style={{
          background: 'linear-gradient(135deg, #f8f9fa, #e8f4ff)',
          padding: '60px 0',
          marginTop: '100px'
        }}
      >
        <div className="container">
          <div className="text-center mb-4">
            <h1 className="fw-bold" style={{ color: 'var(--primary-color)' }}>Privacy Policy</h1>
            <p className="text-muted">Effective Date: December 01, 2025</p>
          </div>

          <div className="mx-auto" style={{ maxWidth: 900 }}>
            <div className="glass-card">
              <div className="mb-4">
                <p className="text-muted">
                  Zepfter ("Zepfter," "we," "our," or "us") recognizes the importance of maintaining the privacy and security of personal information. This Privacy Policy ("Policy") sets forth the terms and conditions under which Zepfter collects, processes, and safeguards personal data provided by users ("User," "you," "your") of the Zepfter pharmaceutical services platform ("Service"). By accessing or using the Service, you acknowledge that you have read, understood, and agree to the terms of this Policy.
                </p>
              </div>

              <section className="mt-4">
                <h5 className="fw-semibold">1. Data Collection</h5>
                <p className="text-muted">Zepfter may collect and process personal data through the following means:</p>
                
                <h6 className="fw-semibold mt-3">1.1. Information Provided Voluntarily</h6>
                <ul className="text-muted">
                  <li>Contact details, such as name and email address, provided during account registration or when communicating with Zepfter.</li>
                  <li>Professional credentials and licensing information for healthcare professionals.</li>
                  <li>Documents, pharmaceutical queries, and content uploaded by Users to the Service.</li>
                  <li>Payment and billing information, as applicable.</li>
                </ul>

                <h6 className="fw-semibold mt-3">1.2. Information Collected Automatically</h6>
                <ul className="text-muted">
                  <li>Technical data, including IP address, browser type, access times, and device identifiers.</li>
                  <li>Usage data and interaction logs generated by User activity within the Service.</li>
                  <li>AI interaction data, including queries and responses to improve our services.</li>
                  <li>Cookies and tracking technologies employed to enhance User experience and improve Service performance.</li>
                </ul>

                <h6 className="fw-semibold mt-3">1.3. Healthcare Data</h6>
                <p className="text-muted">
                  If you choose to upload healthcare or patient data, you must ensure it is de-identified and complies with applicable privacy laws (HIPAA, GDPR, etc.). Zepfter is not responsible for any personally identifiable health information you upload without proper de-identification.
                </p>
              </section>

              <section className="mt-4">
                <h5 className="fw-semibold">2. Purpose of Processing</h5>
                <p className="text-muted">Zepfter processes personal data for the following purposes:</p>
                <ul className="text-muted">
                  <li>Provision, maintenance, and enhancement of the Zepfter platform and associated pharmaceutical services.</li>
                  <li>Facilitation of User interactions, including pharmaceutical research, drug information queries, and AI-powered features.</li>
                  <li>Training and improvement of AI models using de-identified and aggregated data.</li>
                  <li>Verification of healthcare professional credentials and licensing.</li>
                  <li>Processing of payments and billing transactions.</li>
                  <li>Communication with Users regarding updates, services, and important notices.</li>
                  <li>Compliance with applicable legal obligations and regulatory requirements.</li>
                  <li>Protection of the security, integrity, and lawful use of the Service.</li>
                  <li>Analytics and research to enhance user experience and service quality.</li>
                </ul>
              </section>

              <section className="mt-4">
                <h5 className="fw-semibold">3. Data Sharing and Disclosure</h5>
                <p className="text-muted">Zepfter shall not disclose or sell personal data to third parties, except as specified herein:</p>
                <ul className="text-muted">
                  <li>Personal data may be shared with cloud infrastructure providers and service providers engaged by Zepfter for the secure hosting, delivery, and operation of the Service.</li>
                  <li>Data may be shared with AI model providers and technology partners to deliver AI-powered features.</li>
                  <li>Disclosure may occur if required by applicable law, regulation, valid legal process, or regulatory authorities.</li>
                  <li>Information may be shared in connection with mergers, acquisitions, or sale of business assets.</li>
                  <li>Data may be shared with your consent or at your direction.</li>
                  <li>Users retain control over sharing their pharmaceutical research and content with other parties via the Service.</li>
                </ul>
              </section>

              <section className="mt-4">
                <h5 className="fw-semibold">4. Data Retention</h5>
                <p className="text-muted">
                  Zepfter shall retain personal data only for as long as necessary to fulfill the purposes described in this Policy or as otherwise required by law. Uploaded documents and associated data shall be retained for a period of 180 days for guest users, subject to manual deletion upon verified User request.
                </p>
                <p className="text-muted">
                  For any user account that is inactive for a period of 12 months, the uploaded documents and associated data shall be deleted after 12 months of inactivity.
                </p>
                <p className="text-muted">
                  Healthcare-related data may be subject to longer retention periods as required by applicable medical and pharmaceutical regulations.
                </p>
              </section>

              <section className="mt-4">
                <h5 className="fw-semibold">5. Security Measures</h5>
                <p className="text-muted">
                  Zepfter implements appropriate technical and organizational measures to ensure the confidentiality, integrity, and availability of personal data. These measures include, but are not limited to:
                </p>
                <ul className="text-muted">
                  <li>Encryption of data in transit and at rest.</li>
                  <li>Access controls to limit data processing to authorized personnel.</li>
                  <li>Regular assessments and testing of security systems.</li>
                  <li>Secure authentication and session management.</li>
                  <li>Monitoring and logging of system activities.</li>
                  <li>Incident response and data breach notification procedures.</li>
                </ul>
                <p className="text-muted">
                  However, no system is completely secure. You are responsible for protecting your account credentials and notifying us immediately of any unauthorized access.
                </p>
              </section>

              <section className="mt-4">
                <h5 className="fw-semibold">6. AI and Machine Learning</h5>
                
                <h6 className="fw-semibold mt-3">6.1. AI Training</h6>
                <p className="text-muted">
                  Your interactions with AI features may be used to train and improve our models. All data used for training is de-identified and aggregated to protect your privacy. Personal and patient data will be stripped of all identifying information before use in training.
                </p>

                <h6 className="fw-semibold mt-3">6.2. AI-Generated Content</h6>
                <p className="text-muted">
                  Content generated by our AI systems is not stored with your personal identifiers unless you explicitly save it to your account. AI-generated responses are created based on your inputs and our pharmaceutical databases.
                </p>
              </section>

              <section className="mt-4">
                <h5 className="fw-semibold">7. User Rights and Controls</h5>
                <p className="text-muted">Users may:</p>
                <ul className="text-muted">
                  <li>Access and update their Zepfter account information by logging into the Service.</li>
                  <li>Request deletion of uploaded content and associated personal data by submitting a request to support@zepfter.com.</li>
                  <li>Request a copy of their personal information in a structured, machine-readable format.</li>
                  <li>Object to certain processing activities or request restriction of processing.</li>
                  <li>Withdraw consent for data processing where consent was the legal basis.</li>
                  <li>Opt-out of marketing communications at any time.</li>
                  <li>Lodge a complaint with their local data protection supervisory authority.</li>
                </ul>
                <p className="text-muted">
                  To exercise these rights, contact us at privacy@zepfter.com. We will respond within the timeframe required by applicable law.
                </p>
              </section>

              <section className="mt-4">
                <h5 className="fw-semibold">8. Cookies and Tracking Technologies</h5>
                <p className="text-muted">
                  We use cookies, web beacons, and similar technologies to enhance user experience, analyze usage patterns, remember your preferences, and deliver personalized content. You can manage cookie preferences through your browser settings, though disabling cookies may limit certain functionality of the Service.
                </p>
              </section>

              <section className="mt-4">
                <h5 className="fw-semibold">9. Third-Party Services</h5>
                <p className="text-muted">
                  The Service may contain links to third-party websites, services, or pharmaceutical databases. Zepfter assumes no responsibility for the privacy practices or policies of such third parties. Users are encouraged to review applicable privacy policies before providing personal information to third parties.
                </p>
              </section>

              <section className="mt-4">
                <h5 className="fw-semibold">10. Healthcare Data Compliance</h5>
                
                <h6 className="fw-semibold mt-3">10.1. HIPAA Compliance (United States)</h6>
                <p className="text-muted">
                  If you are a covered entity under HIPAA, you are responsible for ensuring compliance with HIPAA requirements. You must de-identify all protected health information (PHI) before uploading to the Service. Zepfter provides technical safeguards but does not act as a Business Associate under HIPAA unless a separate Business Associate Agreement is executed.
                </p>

                <h6 className="fw-semibold mt-3">10.2. GDPR Compliance (European Union/EEA)</h6>
                <p className="text-muted">
                  For users in the European Economic Area, Zepfter complies with GDPR requirements. Our legal basis for processing includes consent, contractual necessity, legitimate interests, and legal obligations. You have the right to access, rectify, erase, restrict processing, data portability, and object to processing.
                </p>

                <h6 className="fw-semibold mt-3">10.3. Other Jurisdictions</h6>
                <p className="text-muted">
                  Zepfter strives to comply with applicable data protection and healthcare privacy laws in all jurisdictions where we operate.
                </p>
              </section>

              <section className="mt-4">
                <h5 className="fw-semibold">11. International Data Transfers</h5>
                <p className="text-muted">
                  Your information may be transferred to and processed in countries other than your own. We ensure appropriate safeguards are in place to protect your data in accordance with this Privacy Policy and applicable laws, including standard contractual clauses and adequacy decisions.
                </p>
              </section>

              <section className="mt-4">
                <h5 className="fw-semibold">12. Children's Privacy</h5>
                <p className="text-muted">
                  The Service is not intended for use by individuals under the age of 18. Zepfter does not knowingly collect personal data from minors. If such data is inadvertently collected, it will be promptly deleted upon discovery.
                </p>
              </section>

              <section className="mt-4">
                <h5 className="fw-semibold">13. California Privacy Rights</h5>
                <p className="text-muted">
                  California residents have additional rights under the California Consumer Privacy Act (CCPA), including the right to know what personal information is collected, the right to delete personal information, the right to opt-out of the sale of personal information, and the right to non-discrimination. Zepfter does not sell personal information.
                </p>
              </section>

              <section className="mt-4">
                <h5 className="fw-semibold">14. Modifications to This Policy</h5>
                <p className="text-muted">
                  Zepfter reserves the right to amend this Policy at its sole discretion to reflect changes in applicable laws, regulations, or business practices. Updated versions shall be posted on this page, with the effective date duly revised. Material changes will be communicated through email or prominent notice on the Service. Continued use of the Service after the effective date constitutes acceptance of the revised Policy.
                </p>
              </section>

              <section className="mt-4">
                <h5 className="fw-semibold">15. Contact Information</h5>
                <p className="text-muted">
                  For questions, concerns, or requests regarding this Privacy Policy or the processing of personal data, Users may contact Zepfter at:
                </p>
                <div className="text-muted">
                  <p className="mb-1">📧 <strong>Support:</strong> support@zepfter.com</p>
                  <p className="mb-1">📧 <strong>Privacy:</strong> privacy@zepfter.com</p>
                  <p className="mb-1">📧 <strong>Data Protection Officer:</strong> dpo@zepfter.com</p>
                  <p className="mb-1">📍 <strong>Address:</strong> [Your Company Address]</p>
                </div>
              </section>

              <div className="mt-5 p-3" style={{ background: '#f8f9fa', borderRadius: '8px' }}>
                <p className="text-muted mb-0">
                  This Privacy Policy constitutes the entire understanding between Zepfter and Users regarding the collection and processing of personal data in connection with the Zepfter pharmaceutical services platform.
                </p>
              </div>

              <div className="mt-4 text-end">
                <a href="/contact" className="btn btn-gradient">Contact Us</a>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};

export default Privacy;
