import React from 'react';

const Privacy = () => {
  return (
    <div>
      <section
        className="section"
        style={{
          background: 'linear-gradient(135deg, #f8f9fa, #e8f4ff)',
          padding: '60px 0',
          marginTop: '100px'
        }}
      >
        <div className="container">
          <div className="text-center mb-4">
            <h1 className="fw-bold" style={{ color: 'var(--primary-color)' }}>Privacy Policy</h1>
            <p className="text-muted">Effective Date: December 01, 2025</p>
          </div>

          <div className="mx-auto" style={{ maxWidth: 900 }}>
            <div className="glass-card">
              <div className="mb-4">
                <p className="text-muted">
                  This Privacy Policy describes how Zepfter ("we," "us," or "our") collects, uses, and protects your personal information when you use our pharmaceutical services platform. By using our Service, you consent to the practices described in this Privacy Policy.
                </p>
              </div>

              <section className="mt-4">
                <h5 className="fw-semibold">1. Information We Collect</h5>
                
                <h6 className="fw-semibold mt-3">1.1 Information You Provide</h6>
                <p className="text-muted">
                  We collect information you provide directly, including account registration details (name, email, professional credentials), uploaded content (pharmaceutical queries, research data), and payment information if applicable.
                </p>

                <h6 className="fw-semibold mt-3">1.2 Healthcare Information</h6>
                <p className="text-muted">
                  If you choose to upload healthcare or patient data, you must ensure it is de-identified and complies with applicable privacy laws (HIPAA, GDPR, etc.). We are not responsible for any personally identifiable health information you upload.
                </p>

                <h6 className="fw-semibold mt-3">1.3 Automatically Collected Information</h6>
                <p className="text-muted">
                  We automatically collect usage data (features accessed, search queries), device information (IP address, browser type, operating system), and AI interaction data to improve our services.
                </p>
              </section>

              <section className="mt-4">
                <h5 className="fw-semibold">2. How We Use Information</h5>
                <p className="text-muted">We use collected information to:</p>
                <ul className="text-muted">
                  <li>Provide, maintain, and improve our pharmaceutical services and AI features</li>
                  <li>Process your requests and respond to inquiries</li>
                  <li>Train and improve our AI models (using de-identified data)</li>
                  <li>Ensure security and prevent fraud or abuse</li>
                  <li>Communicate with you about updates, services, and important notices</li>
                  <li>Comply with legal obligations and regulatory requirements</li>
                  <li>Conduct analytics and research to enhance user experience</li>
                </ul>
              </section>

              <section className="mt-4">
                <h5 className="fw-semibold">3. AI and Machine Learning</h5>
                
                <h6 className="fw-semibold mt-3">3.1 AI Training</h6>
                <p className="text-muted">
                  Your interactions with our AI features may be used to train and improve our models. All data used for training is de-identified and aggregated to protect your privacy.
                </p>

                <h6 className="fw-semibold mt-3">3.2 AI-Generated Content</h6>
                <p className="text-muted">
                  Content generated by our AI systems is not stored with your personal identifiers unless you explicitly save it to your account.
                </p>
              </section>

              <section className="mt-4">
                <h5 className="fw-semibold">4. Information Sharing and Disclosure</h5>
                <p className="text-muted">We do not sell your personal information. We may share information with:</p>
                <ul className="text-muted">
                  <li><strong>Service Providers:</strong> Third-party vendors who assist in operating our platform (cloud hosting, payment processing, analytics)</li>
                  <li><strong>Professional Compliance:</strong> Regulatory authorities when required by law or to protect public health</li>
                  <li><strong>Business Transfers:</strong> In connection with mergers, acquisitions, or sale of assets</li>
                  <li><strong>Legal Requirements:</strong> When necessary to comply with legal obligations, court orders, or protect rights and safety</li>
                  <li><strong>With Your Consent:</strong> When you explicitly authorize us to share information</li>
                </ul>
              </section>

              <section className="mt-4">
                <h5 className="fw-semibold">5. Data Security</h5>
                <p className="text-muted">
                  We implement industry-standard security measures including encryption, access controls, and regular security assessments. However, no system is completely secure. You are responsible for protecting your account credentials and notifying us immediately of any unauthorized access.
                </p>
              </section>

              <section className="mt-4">
                <h5 className="fw-semibold">6. Data Retention</h5>
                <p className="text-muted">
                  We retain your information for as long as necessary to provide services, comply with legal obligations, resolve disputes, and enforce our agreements. You may request deletion of your account and data, subject to legal retention requirements.
                </p>
              </section>

              <section className="mt-4">
                <h5 className="fw-semibold">7. Your Rights and Choices</h5>
                <p className="text-muted">Depending on your location, you may have the right to:</p>
                <ul className="text-muted">
                  <li><strong>Access:</strong> Request a copy of your personal information</li>
                  <li><strong>Correction:</strong> Update or correct inaccurate information</li>
                  <li><strong>Deletion:</strong> Request deletion of your data (subject to legal requirements)</li>
                  <li><strong>Portability:</strong> Receive your data in a structured, machine-readable format</li>
                  <li><strong>Opt-Out:</strong> Unsubscribe from marketing communications</li>
                  <li><strong>Restrict Processing:</strong> Limit how we use your information</li>
                  <li><strong>Object:</strong> Object to certain processing activities</li>
                </ul>
                <p className="text-muted">
                  To exercise these rights, contact us at privacy@zepfter.com. We will respond within the timeframe required by applicable law.
                </p>
              </section>

              <section className="mt-4">
                <h5 className="fw-semibold">8. Cookies and Tracking Technologies</h5>
                <p className="text-muted">
                  We use cookies, web beacons, and similar technologies to enhance user experience, analyze usage patterns, and remember your preferences. You can manage cookie preferences through your browser settings, though disabling cookies may limit functionality.
                </p>
              </section>

              <section className="mt-4">
                <h5 className="fw-semibold">9. Third-Party Links and Services</h5>
                <p className="text-muted">
                  Our Service may contain links to third-party websites or integrate third-party services. We are not responsible for the privacy practices of these external sites. We encourage you to review their privacy policies.
                </p>
              </section>

              <section className="mt-4">
                <h5 className="fw-semibold">10. International Data Transfers</h5>
                <p className="text-muted">
                  Your information may be transferred to and processed in countries other than your own. We ensure appropriate safeguards are in place to protect your data in accordance with this Privacy Policy and applicable laws.
                </p>
              </section>

              <section className="mt-4">
                <h5 className="fw-semibold">11. Children's Privacy</h5>
                <p className="text-muted">
                  Our Service is not intended for individuals under 18 years of age. We do not knowingly collect personal information from children. If we become aware of such collection, we will delete the information promptly.
                </p>
              </section>

              <section className="mt-4">
                <h5 className="fw-semibold">12. Healthcare Data Compliance</h5>
                
                <h6 className="fw-semibold mt-3">12.1 HIPAA Compliance (US)</h6>
                <p className="text-muted">
                  If you are a covered entity under HIPAA, you are responsible for ensuring compliance. We provide technical safeguards, but you must de-identify protected health information before uploading.
                </p>

                <h6 className="fw-semibold mt-3">12.2 GDPR Compliance (EU/EEA)</h6>
                <p className="text-muted">
                  For users in the European Economic Area, we comply with GDPR requirements. Our legal basis for processing includes consent, contractual necessity, and legitimate interests.
                </p>

                <h6 className="fw-semibold mt-3">12.3 Other Jurisdictions</h6>
                <p className="text-muted">
                  We strive to comply with applicable data protection laws in all jurisdictions where we operate.
                </p>
              </section>

              <section className="mt-4">
                <h5 className="fw-semibold">13. California Privacy Rights</h5>
                <p className="text-muted">
                  California residents have additional rights under the California Consumer Privacy Act (CCPA), including the right to know what personal information is collected, the right to delete personal information, and the right to opt-out of the sale of personal information. We do not sell personal information.
                </p>
              </section>

              <section className="mt-4">
                <h5 className="fw-semibold">14. Changes to This Privacy Policy</h5>
                <p className="text-muted">
                  We may update this Privacy Policy from time to time. Material changes will be communicated through email or prominent notice on our platform. Your continued use of the Service after changes constitutes acceptance of the updated policy.
                </p>
              </section>

              <section className="mt-4">
                <h5 className="fw-semibold">15. Contact Us</h5>
                <p className="text-muted">
                  If you have questions, concerns, or requests regarding this Privacy Policy or our data practices, please contact us at:
                </p>
                <div className="text-muted">
                  <p className="mb-1"><strong>Email:</strong> privacy@zepfter.com</p>
                  <p className="mb-1"><strong>Support:</strong> support@zepfter.com</p>
                  <p className="mb-1"><strong>Address:</strong> [Your Company Address]</p>
                  <p className="mb-1"><strong>Data Protection Officer:</strong> dpo@zepfter.com (if applicable)</p>
                </div>
              </section>

              <section className="mt-4">
                <h5 className="fw-semibold">16. Supervisory Authority</h5>
                <p className="text-muted">
                  If you are located in the EU/EEA, you have the right to lodge a complaint with your local data protection supervisory authority if you believe we have violated your privacy rights.
                </p>
              </section>

              <div className="mt-5 p-3" style={{ background: '#f8f9fa', borderRadius: '8px' }}>
                <p className="text-muted mb-0">
                  <strong>Acknowledgment:</strong> By using Zepfter, you acknowledge that you have read and understood this Privacy Policy and agree to its terms.
                </p>
              </div>

              <div className="mt-4 text-end">
                <a href="/contact" className="btn btn-gradient">Contact Us</a>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};

export default Privacy;
